web_nginx/secure/forms.py
#coding=utf-8
from flask_wtf import FlaskForm
from wtforms import StringField,PasswordField,ValidationError,SubmitField,\
    TextAreaField,SelectField,BooleanField,FileField,SelectMultipleField
from wtforms.validators import Email,EqualTo,Length,DataRequired,IPAddress
from flask_wtf.file import FileRequired,FileAllowed
from ..models import *


#SelectMultipleField一直验证报错，然而感觉并没什么错，去掉验证
class SMF(SelectMultipleField):
    def pre_validate (self,form):
        pass

#子网行为增加表单
class SubnetActionAddForm(FlaskForm):
    name = StringField(validators=[DataRequired(),Length(1,64)],
                       render_kw={'required':'',
                                  'lay-verify':'required',
                                  'autocomplete':'off',
                                  'class':'layui-input',
                                  })
    description = StringField(validators=[DataRequired(),Length(1,64)],
                              render_kw={'required': '',
                                         'lay-verify': 'required',
                                         'autocomplete': 'off',
                                         'class': 'layui-input'})
    subnet = StringField(validators=[DataRequired()],
                     render_kw={'required': '',
                                'lay-verify': 'required',
                                'autocomplete': 'off',
                                'class': 'layui-input'}
                     )

    action_choice = ((1,'allow'),(2,'deny'))
    action = SelectField(coerce=int,choices=action_choice)

    submmit = SubmitField('Add',render_kw={'class':'layui-btn',
                                          'lay-filter':'add',
                                          'lay-submit':''})

    def validate_name(self,field):
        if InsideWeb.query.filter_by(name = field.data).first():
            raise ValidationError('命名重复')


#反代安全策略编辑表单
class SecurePolicyEditForm(FlaskForm):
    name = StringField(validators=[DataRequired(),Length(1,64)],
                       render_kw={'required':'',
                                  'readonly':'readonly',
                                  'autocomplete':'off',
                                  'class':'layui-input',
                                  })
    outside_web = StringField(validators=[DataRequired()],
                     render_kw={'required': '',
                                'readonly':'readonly',
                                'autocomplete': 'off',
                                'class': 'layui-input'}
                     )

    is_effect_choice = ((1,'Effect'),(0,'UnEffect'))
    is_effect = SelectField(coerce=int,choices=is_effect_choice)
    subnet_action = SelectMultipleField(coerce=int,
                             render_kw={
                                 'multiple':'multiple',
                                 'lay-ignore':'lay-ignore',
                                 'id': 'select1',})

    user = StringField(validators=[DataRequired()],
                     render_kw={'required': '',
                                'readonly':'readonly',
                                'autocomplete': 'off',
                                'class': 'layui-input'}
                     )

    submmit = SubmitField('Edit',render_kw={'class':'layui-btn',
                                          'lay-filter':'edit',
                                          'lay-submit':''})

    def __init__(self,*args,**kwargs):
        super(SecurePolicyEditForm,self).__init__(*args,**kwargs)
        self.subnet_action.choices = [(subnet_action.id,('%s--%s'%(subnet_action.subnet,subnet_action.action_choice.get(subnet_action.action))))
                                      for subnet_action in SubnetAction.query.order_by(SubnetAction.id).all()]

web_nginx/secure/__init__.py
from flask import Blueprint

secure = Blueprint('secure',__name__)
from . import views

web_nginx/secure/views.py
#coding=utf-8
from flask import render_template,redirect,url_for,request,flash,abort,make_response
from . import secure
from ..models import *
from flask_login import login_user,logout_user,login_required,current_user
from forms import SubnetActionAddForm,SecurePolicyEditForm
import json

#全局安全策略
#查
#改

#子网行为管理
#查
@secure.route('/subnet_action_list')
@login_required
def subnet_action_list():
    page = request.args.get('page', 1, type=int)
    pagination = SubnetAction.query.order_by(SubnetAction.id.asc()).paginate(page, per_page=5, error_out=False)
    subnet_actions = pagination.items
    return render_template('/secure/subnet_action_list.html',subnet_actions=subnet_actions,pagination=pagination)

#增
@secure.route('/subnet_action_add',methods=['GET','POST'])
@login_required
def subnet_action_add():
    subnet_action_add_form = SubnetActionAddForm()
    if subnet_action_add_form.validate_on_submit():
        new_subnet_action = SubnetAction(
            name= subnet_action_add_form.name.data,
            description= subnet_action_add_form.description.data,
            subnet=subnet_action_add_form.subnet.data,
            action=int(subnet_action_add_form.action.data),
            user = current_user._get_current_object(),
        )
        db.session.add(new_subnet_action)
        db.session.commit()
        return redirect(url_for('secure.subnet_action_list'))
    return render_template('/secure/subnet_action_add.html',subnet_action_add_form=subnet_action_add_form)

#删
@secure.route('/subnet_action_delete',methods=['GET','POST'])
@login_required
def subnet_action_delete():
    delete_id = json.loads(request.form.get('delete_id'))
    subnet_action1 = SubnetAction.query.filter_by(id=delete_id).first()
    if subnet_action1:
        db.session.delete(subnet_action1)
        db.session.commit()
    return redirect(url_for('secure.subnet_action_list'))


#改
@secure.route('/subnet_action_edit',methods=['GET','POST'])
@login_required
def subnet_action_edit():
    pass

#站点安全策略管理
#查
@secure.route('/secure_policy_list')
@login_required
def secure_policy_list():
    page = request.args.get('page', 1, type=int)
    pagination = SecurePolicy.query.order_by(SecurePolicy.id.asc()).paginate(page, per_page=5, error_out=False)
    secure_policys = pagination.items
    return render_template('/secure/secure_policy_list.html',secure_policys=secure_policys,pagination=pagination)

#详情
@secure.route('/secure_policy_list_profile')
@login_required
def secure_policy_list_profile():
    cha_id = request.args.get('cha_id')
    secure_policy1 = SecurePolicy.query.filter_by(id=cha_id).first()
    return render_template('/secure/secure_policy_list_profile.html',secure_policy1=secure_policy1)

#改
@secure.route('/secure_policy_edit',methods=['GET','POST'])
@login_required
def secure_policy_edit():
    secure_policy_edit_form = SecurePolicyEditForm()
    edit_id = request.args.get('edit_id')
    secure_policy1 = SecurePolicy.query.filter_by(id=edit_id).first()
    if secure_policy_edit_form.validate_on_submit():
        subnet_action_list1 = []
        for subnet_action_id in secure_policy_edit_form.subnet_action.data:
            subnet_action1 = SubnetAction.query.filter_by(id=int(subnet_action_id)).first()
            subnet_action_list1.append(subnet_action1)
        secure_policy1.id_effect = secure_policy_edit_form.is_effect.data
        secure_policy1.subnet_action = subnet_action_list1
        db.session.add(secure_policy1)
        db.session.commit()
        return 'ok'
    secure_policy_edit_form.name.data = secure_policy1.name
    secure_policy_edit_form.outside_web.data = secure_policy1.outside_web.name
    secure_policy_edit_form.user.data = secure_policy1.user.username
    secure_policy_edit_form.is_effect.data = int(secure_policy1.id_effect)
    return render_template('/secure/secure_policy_edit.html',
                           secure_policy_edit_form=secure_policy_edit_form,
                           secure_policy1=secure_policy1)

web_nginx/templates/secure/secure_policy_edit.html
<!DOCTYPE html>
<html>
  
  <head>
    <meta charset="UTF-8">
    <title>欢迎页面-EasyNginx1.0</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="./css/font.css">
    <link rel="stylesheet" href="./css/xadmin.css">
    <script type="text/javascript" src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript" src="./lib/layui/layui.js" charset="utf-8"></script>
    <script type="text/javascript" src="./js/xadmin.js"></script>
    <!-- 让IE8/9支持媒体查询，从而兼容栅格 -->
    <!--[if lt IE 9]>
      <script src="https://cdn.staticfile.org/html5shiv/r29/html5.min.js"></script>
      <script src="https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <div class="x-body">
        <form class="layui-form" action="{{ url_for('secure.secure_policy_edit',edit_id=secure_policy1.id) }}" method="post">
            {{ secure_policy_edit_form.hidden_tag() }}
            <div class="layui-form-item">
              <label for="username" class="layui-form-label">
                  名称
              </label>
              <div class="layui-input-inline">
                {{ secure_policy_edit_form.name }}
              </div>
              <div class="layui-form-mid layui-word-aux">
                  <span class="x-red">*</span>唯一标识，不可重复，不可修改
              </div>
          </div>
          <div class="layui-form-item">
              <label for="username" class="layui-form-label">
                  <span class="x-red">*</span>反代站点
              </label>
              <div class="layui-input-inline">
                {{ secure_policy_edit_form.outside_web }}
              </div>
              <div class="layui-form-mid layui-word-aux">
                  <span class="x-red">*</span>反代站点名称
              </div>
          </div>
          <div class="layui-form-item">
              <label for="phone" class="layui-form-label">
                  <span class="x-red">*</span>网段行为
              </label>
              <div class="layui-input-inline">
                    {{ secure_policy_edit_form.subnet_action }}
              </div>
              <div class="layui-form-mid layui-word-aux">
                  <span class="x-red">*</span>网段行为列表
              </div>
          </div>
            <div class="layui-form-item">
              <label for="phone" class="layui-form-label">
                  <span class="x-red">*</span>生效/失效
              </label>
              <div class="layui-input-inline">
                    {{ secure_policy_edit_form.is_effect }}
              </div>
              <div class="layui-form-mid layui-word-aux">
                  <span class="x-red">*</span>选择
              </div>
          </div>
          <div class="layui-form-item">
              <label for="L_email" class="layui-form-label">
                  <span class="x-red">*</span>创建者
              </label>
              <div class="layui-input-inline">
                {{ secure_policy_edit_form.user }}
              </div>
              <div class="layui-form-mid layui-word-aux">
                  <span class="x-red">*</span>创建者名称
              </div>
          </div>
          <div class="layui-form-item">
              <label for="L_repass" class="layui-form-label">
              </label>
                 {{ secure_policy_edit_form.submmit() }}
          </div>
      </form>
    </div>
    <script>

            //选中已有的网段行为
        window.onload = function () {
                var select1 = document.getElementById('select1');
                var options = select1.options;
                {% for subnet_action1 in secure_policy1.subnet_action %}
                    for (var option in options){
                        if ({{ subnet_action1.id }} == options[option].value){
                            console.log(options[option].setAttribute("selected","selected"));
                        }

                }
                {% endfor %}
                };


        layui.use(['form','layer'], function(){
            $ = layui.jquery;
          var form = layui.form
          ,layer = layui.layer;


          //监听提交
          form.on('submit(edit)', function(data){
            console.log(data);
            //发异步，把数据提交给php
              alert('修改成功');
              var index = parent.layer.getFrameIndex(window.name);
              parent.layer.close(index);
          });
          
          
        });
    </script>
    <script>var _hmt = _hmt || []; (function() {
        var hm = document.createElement("script");
        hm.src = "https://hm.baidu.com/hm.js?b393d153aeb26b46e9431fabaf0f6190";
        var s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(hm, s);
      })();</script>
  </body>

</html>

web_nginx/templates/secure/secure_policy_list.html
<!DOCTYPE html>
<html>
  
  <head>
    <meta charset="UTF-8">
    <title>欢迎页面-EasyNginx1.0</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="./css/font.css">
    <link rel="stylesheet" href="./css/xadmin.css">
    <script type="text/javascript" src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript" src="./lib/layui/layui.js" charset="utf-8"></script>
    <script type="text/javascript" src="./js/xadmin.js"></script>
    <!-- 让IE8/9支持媒体查询，从而兼容栅格 -->
    <!--[if lt IE 9]>
      <script src="https://cdn.staticfile.org/html5shiv/r29/html5.min.js"></script>
      <script src="https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  
  <body>
    <div class="x-nav">
      <span class="layui-breadcrumb">
        <a href="">首页</a>
        <a href="">安全配置</a>
        <a>
          <cite>反代安全策略</cite></a>
      </span>
      <a class="layui-btn layui-btn-small" style="line-height:1.6em;margin-top:3px;float:right" href="javascript:location.replace(location.href);" title="刷新">
        <i class="layui-icon" style="line-height:30px">ဂ</i></a>
    </div>
    <div class="x-body">
      <blockquote class="layui-elem-quote">每一个反代站点对应一条安全策略，在创建反代站点时自动创建一条空的安全策略<i class="layui-icon x-show" status='true'>&#xe623;</i>在安全策略中添加子网行为</blockquote>
      <xblock>
          <button class="layui-btn layui-btn-warm"  lay-submit="" lay-filter="sreach" onclick="x_admin_show('新增','{{ url_for("secure.subnet_action_add") }}')"><i class="layui-icon"></i>批量安全策略编辑</button>
        <span class="x-right" style="line-height:40px">共有数据：88 条</span>
      </xblock>
      <table class="layui-table layui-form">
        <thead>
          <tr>
            <th width="20">
              <div class="layui-unselect header layui-form-checkbox" lay-skin="primary"><i class="layui-icon">&#xe605;</i></div>
            </th>
            <th width="30">ID</th>
             <th>名称</th>
            <th width="150">反代站点</th>
            <th width="100">子网行为数</th>
            <th width="50">状态</th>
              <th width="75">创建人</th>
            <th width="160">操作</th>
        </thead>
        <tbody class="x-cate">
        {% for secure_policy in secure_policys %}
          <tr cate-id='1' fid='0' >
            <td>
              <div class="layui-unselect layui-form-checkbox" lay-skin="primary" data-id='2'><i class="layui-icon">&#xe605;</i></div>
            </td>
            <td>{{ secure_policy.id }}</td>
              <td>{{ secure_policy.name }}</td>
            <td>{{ secure_policy.outside_web.name }}</td>
              <td>{{ secure_policy.subnet_action | count }}</td>
            <td>
            {% if secure_policy.id_effect %}
              <input type="checkbox"   name="switch"  lay-text="生效|失效"  lay-skin="switch" value="1" checked disabled >
            {% else %}
              <input type="checkbox"   name="switch"  lay-text="生效|失效"  lay-skin="switch" value="1" disabled >
            {% endif %}
            </td>
              <td>{{ secure_policy.user.username }}</td>
            <td class="td-manage">
              <button class="layui-btn layui-btn layui-btn-xs layui-btn-normal"  onclick="x_admin_show('详情','{{ url_for("secure.secure_policy_list_profile",cha_id=secure_policy.id ) }}')" ><i class="layui-icon">&#xe6a2;</i>详情</button>
              <button class="layui-btn layui-btn layui-btn-xs layui-btn-warm"  onclick="x_admin_show('编辑','{{ url_for("secure.secure_policy_edit",edit_id=secure_policy.id) }}')" ><i class="layui-icon">&#xe642;</i>编辑</button>
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
    <style type="text/css">
      
    </style>
    <script>
      layui.use(['form'], function(){
        form = layui.form;
        
      });




      function delAll (argument) {

        var data = tableCheck.getData();
  
        layer.confirm('确认要删除吗？'+data,function(index){
            //捉到所有被选中的，发异步进行删除
            layer.msg('删除成功', {icon: 1});
            $(".layui-form-checked").not('.header').parents('tr').remove();
        });
      }
    </script>
    <script>var _hmt = _hmt || []; (function() {
        var hm = document.createElement("script");
        hm.src = "https://hm.baidu.com/hm.js?b393d153aeb26b46e9431fabaf0f6190";
        var s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(hm, s);
      })();</script>
  </body>

</html>

web_nginx/templates/secure/subnet_action_add.html
<!DOCTYPE html>
<html>
  
  <head>
    <meta charset="UTF-8">
    <title>欢迎页面-EasyNginx1.0</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="./css/font.css">
    <link rel="stylesheet" href="./css/xadmin.css">
    <script type="text/javascript" src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript" src="./lib/layui/layui.js" charset="utf-8"></script>
    <script type="text/javascript" src="./js/xadmin.js"></script>
    <!-- 让IE8/9支持媒体查询，从而兼容栅格 -->
    <!--[if lt IE 9]>
      <script src="https://cdn.staticfile.org/html5shiv/r29/html5.min.js"></script>
      <script src="https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  
  <body>
    <div class="x-body">
        <form class="layui-form" action="{{ url_for('secure.subnet_action_add') }}" method="post">
            {{ subnet_action_add_form.hidden_tag() }}
          <div class="layui-form-item">
              <label for="username" class="layui-form-label">
                  <span class="x-red">*</span>名称
              </label>
              <div class="layui-input-inline">
                  {{ subnet_action_add_form.name }}
              </div>
              <div class="layui-form-mid layui-word-aux">
                  <span class="x-red">*</span>唯一标识，不可重复，不可修改，例如：test_net
              </div>
          </div>
          <div class="layui-form-item">
              <label for="username" class="layui-form-label">
                  <span class="x-red">*</span>描述
              </label>
              <div class="layui-input-inline">
                  {{ subnet_action_add_form.description }}
              </div>
              <div class="layui-form-mid layui-word-aux">
                  <span class="x-red">*</span>例如：测试网段
              </div>
          </div>
          <div class="layui-form-item">
              <label for="phone" class="layui-form-label">
                  <span class="x-red">*</span>子网
              </label>
              <div class="layui-input-inline">
                  {{ subnet_action_add_form.subnet }}
              </div>
              <div class="layui-form-mid layui-word-aux">
                  <span class="x-red">*</span>子网网段
              </div>
          </div>
          <div class="layui-form-item">
              <label for="L_email" class="layui-form-label">
                  <span class="x-red">*</span>行为
              </label>
              <div class="layui-input-inline">
                  {{ subnet_action_add_form.action }}
              </div>
              <div class="layui-form-mid layui-word-aux">
                  <span class="x-red">*</span>允许或拒绝
              </div>
          </div>
          <div class="layui-form-item">
              <label for="L_repass" class="layui-form-label">
              </label>
                {{ subnet_action_add_form.submmit() }}
          </div>
      </form>
    </div>
    <script>
        layui.use(['form','layer'], function(){
            $ = layui.jquery;
          var form = layui.form
          ,layer = layui.layer;
        
          //自定义验证规则
          form.verify({
            nikename: function(value){
              if(value.length < 5){
                return '昵称至少得5个字符啊';
              }
            }
            ,pass: [/(.+){6,12}$/, '密码必须6到12位']
            ,repass: function(value){
                if($('#L_pass').val()!=$('#L_repass').val()){
                    return '两次密码不一致';
                }
            }
          });

          //监听提交
          form.on('submit(add)', function(data){
            //发异步，把数据提交给php
              alert('增加成功');
              var index = parent.layer.getFrameIndex(window.name);
              parent.layer.close(index);
          });
          
          
        });
    </script>
    <script>var _hmt = _hmt || []; (function() {
        var hm = document.createElement("script");
        hm.src = "https://hm.baidu.com/hm.js?b393d153aeb26b46e9431fabaf0f6190";
        var s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(hm, s);
      })();</script>
  </body>

</html>

web_nginx/templates/secure/subnet_action_list.html
<!DOCTYPE html>
<html>
  
  <head>
    <meta charset="UTF-8">
    <title>欢迎页面-EasyNginx1.0</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="./css/font.css">
    <link rel="stylesheet" href="./css/xadmin.css">
    <script type="text/javascript" src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript" src="./lib/layui/layui.js" charset="utf-8"></script>
    <script type="text/javascript" src="./js/xadmin.js"></script>
    <!-- 让IE8/9支持媒体查询，从而兼容栅格 -->
    <!--[if lt IE 9]>
      <script src="https://cdn.staticfile.org/html5shiv/r29/html5.min.js"></script>
      <script src="https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  
  <body>
    <div class="x-nav">
      <span class="layui-breadcrumb">
        <a href="">首页</a>
        <a href="">安全配置</a>
        <a>
          <cite>子网行为列表</cite></a>
      </span>
      <a class="layui-btn layui-btn-small" style="line-height:1.6em;margin-top:3px;float:right" href="javascript:location.replace(location.href);" title="刷新">
        <i class="layui-icon" style="line-height:30px">ဂ</i></a>
    </div>
    <div class="x-body">
      <blockquote class="layui-elem-quote">每个tr 上有两个属性 cate-id='1' 当前分类id fid='0' 父级id ,顶级分类为 0，有子分类的前面加收缩图标<i class="layui-icon x-show" status='true'>&#xe623;</i></blockquote>
      <xblock>
        <button class="layui-btn layui-btn-danger" onclick="delAll()"><i class="layui-icon"></i>批量删除</button>
          <button class="layui-btn"  lay-submit="" lay-filter="sreach" onclick="x_admin_show('新增','{{ url_for("secure.subnet_action_add") }}')"><i class="layui-icon"></i>新增子网行为</button>
        <span class="x-right" style="line-height:40px">共有数据：88 条</span>
      </xblock>
      <table class="layui-table layui-form">
        <thead>
          <tr>
            <th width="20">
              <div class="layui-unselect header layui-form-checkbox" lay-skin="primary"><i class="layui-icon">&#xe605;</i></div>
            </th>
            <th width="30">ID</th>
             <th width="100">名称</th>
            <th>描述</th>
            <th width="150">子网</th>
            <th width="50">行为</th>
              <th width="75">创建人</th>
            <th width="160">操作</th>
        </thead>
        <tbody class="x-cate">
        {% for subnet_action in subnet_actions %}
          <tr cate-id='1' fid='0' >
            <td>
              <div class="layui-unselect layui-form-checkbox" lay-skin="primary" data-id='2'><i class="layui-icon">&#xe605;</i></div>
            </td>
            <td>{{ subnet_action.id }}</td>
              <td>{{ subnet_action.name }}</td>
            <td>{{ subnet_action.description }}</td>
              <td>{{ subnet_action.subnet }}</td>
            <td>{{ subnet_action.action_choice.get(subnet_action.action) }}</td>
              <td>{{ subnet_action.user.username }}</td>
            <td class="td-manage">
              <button class="layui-btn layui-btn layui-btn-xs layui-btn-warm"  onclick="x_admin_show('编辑','{{ url_for("secure.subnet_action_edit",edit_id=subnet_action.id) }}')" ><i class="layui-icon">&#xe642;</i>编辑</button>
                <button  class="layui-btn-danger layui-btn layui-btn-xs"  onclick="member_del(this,{{ subnet_action.id }})" href="javascript:;" ><i class="layui-icon">&#xe640;</i>删除</button>
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
    <style type="text/css">
      
    </style>
    <script>
      layui.use(['form'], function(){
        form = layui.form;
        
      });

      

      /*用户-删除*/
      function member_del(obj,id){
          layer.confirm('确认要删除吗？',function(index){
              //发异步删除数据
              $(obj).parents("tr").remove();
              layer.msg('已删除!',{icon:1,time:1000});
              console.log(id);
              $.ajax(
                  {
                      type:'post',
                      url:'{{ url_for('secure.subnet_action_delete') }}',
                      data:{'delete_id':id},
                      dataType:'json',
                      success:function (data) {
                            console.log('ok')
                }
                  }
              )
          });
      }



      function delAll (argument) {

        var data = tableCheck.getData();
  
        layer.confirm('确认要删除吗？'+data,function(index){
            //捉到所有被选中的，发异步进行删除
            layer.msg('删除成功', {icon: 1});
            $(".layui-form-checked").not('.header').parents('tr').remove();
        });
      }
    </script>
    <script>var _hmt = _hmt || []; (function() {
        var hm = document.createElement("script");
        hm.src = "https://hm.baidu.com/hm.js?b393d153aeb26b46e9431fabaf0f6190";
        var s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(hm, s);
      })();</script>
  </body>

</html>