web_nginx/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)
from . import views

web_nginx/main/views.py
#coding=utf-8
from flask import render_template,redirect,url_for,request,flash,abort
from . import main
from ..models import *
from .forms import InsideWebEditForm,InsideWebAddForm,OutsideWebAddForm,OutsideWebEditForm,CsrfToken
from flask_login import login_user,logout_user,login_required,current_user
import json,os
from templates_handle import config_outside_web,\
    send_modified_config,get_outside_web_conf,compare_file,\
    read_file,switch_site_state,delete_nginx_sub_conf
from config import basedir

#首页
@main.route('/')
@login_required
def index():
    return render_template('index.html')

#首页桌面
@main.route('/welcome')
@login_required
def welcome():
    return render_template('welcome.html')

#生效配置
@main.route('/effect_config',methods=['GET','POST'])
@login_required
def effect_config():
    modified_outside_webs = OutsideWeb.query.filter_by(is_update=True).all()
    modified_outside_webs_dict = {}
    for modified_outside_web1 in modified_outside_webs:
        modified_outside_webs_dict.update(
            { modified_outside_web1.name :{
                'filename':modified_outside_web1.new_config_path.split('\\')[-1],
                'file':get_outside_web_conf(modified_outside_web1),
                'id':modified_outside_web1.id,
            } }
        )
    csrf_token = CsrfToken()
    if csrf_token.validate_on_submit():
        send_modified_config()
    return render_template('/main/effect_config.html',
                           modified_outside_webs_dict=modified_outside_webs_dict,
                           csrf_token=csrf_token)

#站点管理
#外部站点管理
#查
@main.route('/outside_web_list',methods=['GET','POST'])
@login_required
def outside_web_list():
    outside_webs = OutsideWeb.query.all()
    if request.method == 'POST':
        print('ok')
    return render_template('/main/outside_web_list.html',outside_webs=outside_webs)

@main.route('/outside_web_list_profile')
def outside_web_list_profile():
    cha_id = request.args.get('cha_id')
    outside_web1 = OutsideWeb.query.filter_by(id=cha_id).first()
    return render_template('/main/outside_web_list_profile.html',outside_web1=outside_web1)

#改
@main.route('/outside_web_edit',methods=['GET','POST'])
@login_required
def outside_web_edit():
    edit_id = request.args.get('edit_id')
    outside_web1 = OutsideWeb.query.filter_by(id=edit_id).first()
    outside_web_edit_form = OutsideWebEditForm()
    if outside_web_edit_form.validate_on_submit():
        inside_web_list1 = []
        for inside_web_id in outside_web_edit_form.inside_web.data:
            inside_web1 = InsideWeb.query.filter_by(id=int(inside_web_id)).first()
            inside_web_list1.append(inside_web1)
        outside_web1.description = outside_web_edit_form.description.data
        outside_web1.domain = outside_web_edit_form.domain.data
        outside_web1.port = int(outside_web_edit_form.port.data)
        outside_web1.network_protocol = int(outside_web_edit_form.network_protocol.data)
        outside_web1.application_protocol = int(outside_web_edit_form.application_protocol.data)
        outside_web1.state = int(outside_web_edit_form.state.data)
        outside_web1.inside_web = inside_web_list1
        outside_web1.update_update_time()
        config_outside_web(outside_web1)
        db.session.add(outside_web1)
        db.session.commit()
        return 'ok'
    outside_web_edit_form.name.data = outside_web1.name
    outside_web_edit_form.description.data = outside_web1.description
    outside_web_edit_form.domain.data = outside_web1.domain
    outside_web_edit_form.port.data = outside_web1.port
    outside_web_edit_form.network_protocol.data = outside_web1.network_protocol
    outside_web_edit_form.application_protocol.data = outside_web1.application_protocol
    for _inside_web in outside_web1.inside_web:
        outside_web_edit_form.inside_web.choices.append((_inside_web.id,_inside_web.name))
    outside_web_edit_form.inside_web.data = outside_web1.inside_web
    outside_web_edit_form.state.data = outside_web1.state
    return render_template('/main/outside_web_edit.html',
                           outside_web_edit_form=outside_web_edit_form,
                           outside_web1=outside_web1)

#增
@main.route('/outside_web_add',methods=['GET','POST'])
@login_required
def outside_web_add():
    outside_web_add_form = OutsideWebAddForm()
    if outside_web_add_form.validate_on_submit():
        inside_web_list1 = []
        for inside_web_id in outside_web_add_form.inside_web.data:
            inside_web1 = InsideWeb.query.filter_by(id=int(inside_web_id)).first()
            inside_web_list1.append(inside_web1)
        outside_web1 = OutsideWeb(
            name=outside_web_add_form.name.data,
            description=outside_web_add_form.description.data,
            domain=outside_web_add_form.domain.data,
            port=int(outside_web_add_form.port.data),
            network_protocol=int(outside_web_add_form.network_protocol.data),
            application_protocol=int(outside_web_add_form.application_protocol.data),
            inside_web=inside_web_list1,
            user = current_user._get_current_object(),
            state= 1
        )
        db.session.add(outside_web1)
        db.session.commit()
        outside_web1.update_update_time()
        outside_web1.create_secure_policy()
        config_outside_web(outside_web1)
    return render_template('/main/outside_web_add.html',outside_web_add_form=outside_web_add_form)

#删
@main.route('/outside_web_delete',methods=['GET','POST'])
@login_required
def outside_web_delete():
    if request.method == 'POST':
        delete_id = json.loads(request.form.get('delete_id'))
        outside_web1 = OutsideWeb.query.filter_by(id=delete_id).first()
        if outside_web1:
            outside_web1.delete_secure_policy()
            delete_nginx_sub_conf(outside_web1)
            db.session.delete(outside_web1)
            db.session.commit()
        return redirect(url_for('main.outside_web_list'))

#内部站点管理
#查
@main.route('/inside_web_list')
@login_required
def inside_web_list():
    inside_webs = InsideWeb.query.all()
    return render_template('/main/inside_web_list.html',inside_webs=inside_webs)

#改
@login_required
@main.route('/inside_web_edit',methods=['GET','POST'])
def inside_web_edit():
    inside_web_edit_form =InsideWebEditForm()
    edit_id = request.args.get('edit_id')
    inside_web1 = InsideWeb.query.filter_by(id=edit_id).first()
    if inside_web_edit_form.validate_on_submit():
        inside_web1.description = inside_web_edit_form.description.data
        inside_web1.ip = inside_web_edit_form.ip.data
        inside_web1.port = int(inside_web_edit_form.port.data)
        db.session.add(inside_web1)
        db.session.commit()
        return 'ok'
    inside_web_edit_form.name.data = inside_web1.name
    inside_web_edit_form.description.data = inside_web1.description
    inside_web_edit_form.ip.data = inside_web1.ip
    inside_web_edit_form.port.data = str(inside_web1.port)
    return render_template('/main/inside_web_edit.html',
                           inside_web_edit_form=inside_web_edit_form,
                           inside_web1=inside_web1)

#增
@main.route('/inside_web_add',methods=['GET','POST'])
@login_required
def inside_web_add():
    inside_web_add_form = InsideWebAddForm()
    if inside_web_add_form.validate_on_submit():
        inside_web1 = InsideWeb(
            name=inside_web_add_form.name.data,
            description=inside_web_add_form.description.data,
            ip=inside_web_add_form.ip.data,
            port=int(inside_web_add_form.port.data),
            user = current_user._get_current_object()
        )
        db.session.add(inside_web1)
        db.session.commit()
    return render_template('/main/secure.html',inside_web_add_form=inside_web_add_form)

#删
@main.route('/inside_web_delete',methods=['GET','POST'])
@login_required
def inside_web_delete():
    if request.method == 'POST':
        delete_id = json.loads(request.form.get('delete_id'))
        inside_web1 = InsideWeb.query.filter_by(id=delete_id).first()
        if inside_web1:
            db.session.delete(inside_web1)
            db.session.commit()
        return redirect(url_for('main.inside_web_list'))


#全局配置
#基础配置
#查
@main.route('/base_config')
@login_required
def base_config():
    base_config1 = BaseConfig.query.all()[0]
    return render_template('/main/base_config.html',base_config1=base_config1)

#查命令
@main.route('/base_config_cmd')
@login_required
def base_config_cmd():
    base_config_cmd1 = read_file(os.path.join(basedir,'easy_nginx\\static\\conf\\base_config\\base.template.conf'))
    return render_template('/main/base_config_cmd.html',base_config_cmd1=base_config_cmd1)

#改
@main.route('/base_config_edit')
@login_required
def base_config_edit():
    pass

#获取配置比对文件
@main.route('/get_compare_file')
@login_required
def get_compare_file():
    id = request.args.get('id')
    outside_web1 = OutsideWeb.query.filter_by(id=id).first()
    if outside_web1.now_config_path and outside_web1.new_config_path:
        compare_file(outside_web1.now_config_path,outside_web1.new_config_path)
        return render_template('/compare/compare.html')
    else:
        return 'new config'


#测试
@main.route('/test')
def test():
    outside_web1 = OutsideWeb.query.filter_by(id=3).first()
    compare_file(outside_web1.now_config_path,outside_web1.new_config_path)
    return render_template('/compare/compare.html')

web_nginx/templates/main/base_config.html
<!DOCTYPE html>
<html>
  
  <head>
    <meta charset="UTF-8">
    <title>欢迎页面-EasyNginx1.0</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="./css/font.css">
    <link rel="stylesheet" href="./css/xadmin.css">
    <script type="text/javascript" src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript" src="./lib/layui/layui.js" charset="utf-8"></script>
    <script type="text/javascript" src="./js/xadmin.js"></script>
    <!-- 让IE8/9支持媒体查询，从而兼容栅格 -->
    <!--[if lt IE 9]>
      <script src="https://cdn.staticfile.org/html5shiv/r29/html5.min.js"></script>
      <script src="https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  
  <body>
    <div class="x-nav">
      <span class="layui-breadcrumb">
        <a href="">首页</a>
        <a href="">全局配置</a>
        <a>
          <cite>基础配置</cite></a>
      </span>
      <a class="layui-btn layui-btn-small" style="line-height:1.6em;margin-top:3px;float:right" href="javascript:location.replace(location.href);" title="刷新">
        <i class="layui-icon" style="line-height:30px">ဂ</i></a>
    </div>
    <div class="x-body">
      <blockquote class="layui-elem-quote">基础配置已有预设的配置，如果不是特别熟悉配置项，请保持默认配置<i class="layui-icon x-show" status='true'>&#xe623;</i></blockquote>
      <xblock>
        <button class="layui-btn layui-btn-normal"  lay-submit="" lay-filter="sreach" onclick="x_admin_show('命令行基础配置','{{ url_for("main.base_config_cmd") }}')"><i class="layui-icon">&#xe69d;</i>查看命令行配置</button>
          <button class="layui-btn layui-btn-danger"  lay-submit="" lay-filter="sreach" onclick="x_admin_show('编辑','{{ url_for("main.inside_web_add") }}')"><i class="layui-icon">&#xe642;</i>修改基础配置</button>
        <span class="x-right" style="line-height:40px">xxxxx</span>
      </xblock>

        <fieldset class="layui-elem-field">
            <legend>基础配置</legend>
            <div class="layui-field-box">
                <table class="layui-table">
                    <tbody>
                        <tr>
                            <th>进程数</th>
                            <td>{{ base_config1.worker_processes }}</tr>
                        <tr>
                            <th>最大连接数</th>
                            <td>{{ base_config1.worker_connections }}</td></tr>
                        <tr>
                            <th>连接超时时间</th>
                            <td>{{ base_config1.keepalive_timeout }}</td></tr>
                        <tr>
                            <th>上传文件最大</th>
                            <td>{{ base_config1.client_max_body_size }}</td></tr>
                        <tr>
                            <th>最新配置更新时间</th>
                            <td>{{ base_config1.update_time }}</td></tr>
                    </tbody>
                </table>
            </div>
        </fieldset>
        <fieldset class="layui-elem-field">
            <legend>开发团队</legend>
            <div class="layui-field-box">
                <table class="layui-table">
                    <tbody>
                        <tr>
                            <th>版权所有</th>
                            <td>xuebingsi(xuebingsi)
                                <a href="http://x.xuebingsi.com/" class='x-a' target="_blank">访问官网</a></td>
                        </tr>
                        <tr>
                            <th>开发者</th>
                            <td>马志斌(113664000@qq.com)</td></tr>
                    </tbody>
                </table>
            </div>
        </fieldset>
        <blockquote class="layui-elem-quote layui-quote-nm">感谢layui,百度Echarts,jquery,本系统由x-admin提供技术支持。</blockquote>
    </div>

    <style type="text/css">
      
    </style>
    <script>
      layui.use(['form'], function(){
        form = layui.form;
        
      });

      

      /*用户-删除*/
      function member_del(obj,id){
          layer.confirm('确认要删除吗？',function(index){
              //发异步删除数据
              $(obj).parents("tr").remove();
              layer.msg('已删除!',{icon:1,time:1000});
          });
      }



      function delAll (argument) {

        var data = tableCheck.getData();
  
        layer.confirm('确认要删除吗？'+data,function(index){
            //捉到所有被选中的，发异步进行删除
            layer.msg('删除成功', {icon: 1});
            $(".layui-form-checked").not('.header').parents('tr').remove();
        });
      }
    </script>
    <script>var _hmt = _hmt || []; (function() {
        var hm = document.createElement("script");
        hm.src = "https://hm.baidu.com/hm.js?b393d153aeb26b46e9431fabaf0f6190";
        var s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(hm, s);
      })();</script>
  </body>

</html>

web_nginx/templates/main/inside_web_list.html
<!DOCTYPE html>
<html>
  
  <head>
    <meta charset="UTF-8">
    <title>欢迎页面-EasyNginx1.0</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="./css/font.css">
    <link rel="stylesheet" href="./css/xadmin.css">
    <script type="text/javascript" src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript" src="./lib/layui/layui.js" charset="utf-8"></script>
    <script type="text/javascript" src="./js/xadmin.js"></script>
    <!-- 让IE8/9支持媒体查询，从而兼容栅格 -->
    <!--[if lt IE 9]>
      <script src="https://cdn.staticfile.org/html5shiv/r29/html5.min.js"></script>
      <script src="https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  
  <body>
    <div class="x-nav">
      <span class="layui-breadcrumb">
        <a href="">首页</a>
        <a href="">站点管理</a>
        <a>
          <cite>内部站点列表</cite></a>
      </span>
      <a class="layui-btn layui-btn-small" style="line-height:1.6em;margin-top:3px;float:right" href="javascript:location.replace(location.href);" title="刷新">
        <i class="layui-icon" style="line-height:30px">ဂ</i></a>
    </div>
    <div class="x-body">
      <blockquote class="layui-elem-quote">每个tr 上有两个属性 cate-id='1' 当前分类id fid='0' 父级id ,顶级分类为 0，有子分类的前面加收缩图标<i class="layui-icon x-show" status='true'>&#xe623;</i></blockquote>
      <xblock>
        <button class="layui-btn layui-btn-danger" onclick="delAll()"><i class="layui-icon"></i>批量删除</button>
          <button class="layui-btn"  lay-submit="" lay-filter="sreach" onclick="x_admin_show('编辑','{{ url_for("main.inside_web_add") }}')"><i class="layui-icon"></i>新增内部站点</button>
        <span class="x-right" style="line-height:40px">共有数据：88 条</span>
      </xblock>
      <table class="layui-table layui-form">
        <thead>
          <tr>
            <th width="20">
              <div class="layui-unselect header layui-form-checkbox" lay-skin="primary"><i class="layui-icon">&#xe605;</i></div>
            </th>
            <th width="30">ID</th>
             <th width="100">名称</th>
            <th>描述</th>
            <th width="100">IP</th>
            <th width="50">PORT</th>
            <th width="50">状态</th>
              <th width="75">创建人</th>
            <th width="160">操作</th>
        </thead>
        <tbody class="x-cate">
        {% for inside_web in inside_webs %}
          <tr cate-id='1' fid='0' >
            <td>
              <div class="layui-unselect layui-form-checkbox" lay-skin="primary" data-id='2'><i class="layui-icon">&#xe605;</i></div>
            </td>
            <td>{{ inside_web.id }}</td>
              <td>{{ inside_web.name }}</td>
            <td>{{ inside_web.description }}</td>
              <td>{{ inside_web.ip }}</td>
            <td>{{ inside_web.port }}</td>
            <td>
              {% if inside_web.state_check() %}
              <input type="checkbox"   name="switch"  lay-text="在线|离线"  lay-skin="switch" value="1" checked disabled >
            {% else %}
              <input type="checkbox"   name="switch"  lay-text="在线|离线"  lay-skin="switch" value="1" disabled >
            {% endif %}
            </td>
              <td>{{ inside_web.user.username }}</td>
            <td class="td-manage">
              <button class="layui-btn layui-btn layui-btn-xs"  onclick="x_admin_show('编辑','{{ url_for("main.inside_web_edit",edit_id=inside_web.id) }}')" ><i class="layui-icon">&#xe642;</i>编辑</button>
                <button  class="layui-btn-danger layui-btn layui-btn-xs"  onclick="member_del(this,{{ inside_web.id }})" href="javascript:;" ><i class="layui-icon">&#xe640;</i>删除</button>
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
    <style type="text/css">
      
    </style>
    <script>
      layui.use(['form'], function(){
        form = layui.form;
        
      });

      

      /*用户-删除*/
      function member_del(obj,id){
          layer.confirm('确认要删除吗？',function(index){
              //发异步删除数据
              $(obj).parents("tr").remove();
              layer.msg('已删除!',{icon:1,time:1000});
              console.log(id);
              $.ajax(
                  {
                      type:'post',
                      url:'{{ url_for('main.inside_web_delete') }}',
                      data:{'delete_id':id},
                      dataType:'json',
                      success:function (data) {
                            console.log('ok')
                }
                  }
              )
          });
      }



      function delAll (argument) {

        var data = tableCheck.getData();
  
        layer.confirm('确认要删除吗？'+data,function(index){
            //捉到所有被选中的，发异步进行删除
            layer.msg('删除成功', {icon: 1});
            $(".layui-form-checked").not('.header').parents('tr').remove();
        });
      }
    </script>
    <script>var _hmt = _hmt || []; (function() {
        var hm = document.createElement("script");
        hm.src = "https://hm.baidu.com/hm.js?b393d153aeb26b46e9431fabaf0f6190";
        var s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(hm, s);
      })();</script>
  </body>

</html>

web_nginx/templates/main/outside_web_list.html
<!DOCTYPE html>
<html>
  
  <head>
    <meta charset="UTF-8">
    <title>欢迎页面-EasyNginx1.0</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="./css/font.css">
    <link rel="stylesheet" href="./css/xadmin.css">
    <script type="text/javascript" src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript" src="./lib/layui/layui.js" charset="utf-8"></script>
    <script type="text/javascript" src="./js/xadmin.js"></script>
    <!-- 让IE8/9支持媒体查询，从而兼容栅格 -->
    <!--[if lt IE 9]>
      <script src="https://cdn.staticfile.org/html5shiv/r29/html5.min.js"></script>
      <script src="https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  
  <body>
    <div class="x-nav">
      <span class="layui-breadcrumb">
        <a href="">首页</a>
        <a href="">站点管理</a>
        <a>
          <cite>内部站点列表</cite></a>
      </span>
      <a class="layui-btn layui-btn-small" style="line-height:1.6em;margin-top:3px;float:right" href="javascript:location.replace(location.href);" title="刷新">
        <i class="layui-icon" style="line-height:30px">ဂ</i></a>
    </div>
    <div class="x-body">
      <blockquote class="layui-elem-quote">每个tr 上有两个属性 cate-id='1' 当前分类id fid='0' 父级id ,顶级分类为 0，有子分类的前面加收缩图标<i class="layui-icon x-show" status='true'>&#xe623;</i></blockquote>
      <xblock>
        <button class="layui-btn layui-btn-danger" onclick="delAll()"><i class="layui-icon"></i>批量删除</button>
          <button class="layui-btn"  lay-submit="" lay-filter="sreach" onclick="x_admin_show('新增','{{ url_for("main.outside_web_add") }}')"><i class="layui-icon"></i>新增反代站点</button>
        <span class="x-right" style="line-height:40px">共有数据：88 条</span>
      </xblock>
      <table class="layui-table layui-form">
        <thead>
          <tr>
            <th width="20">
              <div class="layui-unselect header layui-form-checkbox" lay-skin="primary"><i class="layui-icon">&#xe605;</i></div>
            </th>
            <th width="30">ID</th>
             <th width="50">名称</th>
            <th>描述</th>
             <th width="150">域名</th>
            <th width="50">状态</th>
              <th width="75">创建人</th>
            <th width="250">操作</th>
        </thead>
        <tbody class="x-cate">
        {% for outside_web in outside_webs %}
          <tr cate-id='1' fid='0' >
            <td>
              <div class="layui-unselect layui-form-checkbox" lay-skin="primary" data-id='2'><i class="layui-icon">&#xe605;</i></div>
            </td>
            <td>{{ outside_web.id }}</td>
              <td>{{ outside_web.name }}</td>
            <td>{{ outside_web.description }}</td>
              <td>{{ outside_web.domain }}</td>
            <td>
            {% if outside_web.state == 1 %}
              <input type="checkbox"   name="switch"  lay-text="上线|下线"  lay-skin="switch" value="1" checked disabled >
            {% else %}
              <input type="checkbox"   name="switch"  lay-text="上线|下线"  lay-skin="switch" value="1" disabled >
            {% endif %}
            </td>
              <td>{{ outside_web.user.username }}</td>
            <td class="td-manage">
              <button class="layui-btn layui-btn layui-btn-xs layui-btn-normal"  onclick="x_admin_show('详情','{{ url_for("main.outside_web_list_profile",cha_id=outside_web.id ) }}')" ><i class="layui-icon">&#xe6a2;</i>详情</button>
              <button class="layui-btn layui-btn layui-btn-xs "  onclick="x_admin_show('编辑','{{ url_for("main.inside_web_edit") }}')" ><i class="layui-icon">&#xe6a2;</i>日志</button>
              <button class="layui-btn layui-btn layui-btn-xs layui-btn-warm"  onclick="x_admin_show('编辑','{{ url_for("main.outside_web_edit",edit_id = outside_web.id) }}')" ><i class="layui-icon">&#xe642;</i>编辑</button>
              <button class="layui-btn-danger layui-btn layui-btn-xs"  onclick="member_del(this,{{ outside_web.id }})" href="javascript:;" ><i class="layui-icon">&#xe640;</i>删除</button>
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>

    <style type="text/css">
      
    </style>
    <script>
      layui.use(['form'], function(){
        form = layui.form;
        
      });


      /*用户-删除*/
      function member_del(obj,id){
          layer.confirm('确认要删除吗？',function(index){
              //发异步删除数据
              $(obj).parents("tr").remove();
              layer.msg('已删除!',{icon:1,time:1000});
                            console.log(id);
              $.ajax(
                  {
                      type:'post',
                      url:'{{ url_for('main.outside_web_delete') }}',
                      data:{'delete_id':id},
                      dataType:'json',
                      success:function (data) {
                            console.log('ok')
                }
                  }
              )

          });
      }



      function delAll (argument) {

        var data = tableCheck.getData();
  
        layer.confirm('确认要删除吗？'+data,function(index){
            //捉到所有被选中的，发异步进行删除
            layer.msg('删除成功', {icon: 1});
            $(".layui-form-checked").not('.header').parents('tr').remove();
        });
      }
    </script>
    <script>var _hmt = _hmt || []; (function() {
        var hm = document.createElement("script");
        hm.src = "https://hm.baidu.com/hm.js?b393d153aeb26b46e9431fabaf0f6190";
        var s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(hm, s);
      })();</script>
  </body>

</html>